# Generated by Django 2.1.7 on 2019-03-08 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_auto_20190307_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intutile', models.CharField(max_length=100, verbose_name='Intitulé du poste')),
                ('description', models.TextField(null=True)),
                ('mission', models.TextField(null=True)),
                ('date_limite', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date limite du candidature')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la publication')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Recruteur')),
            ],
            options={
                'ordering': ['date_publication'],
            },
        ),
    ]
