# Generated by Django 2.1.7 on 2019-03-08 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190307_1420'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cv', models.CharField(max_length=200, verbose_name='Nom CV')),
                ('chemin', models.TextField(null=True)),
                ('date_cv', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de depôt CV')),
                ('candicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Candidat')),
            ],
            options={
                'ordering': ['date_cv'],
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_lettre', models.TextField(null=True)),
                ('date_postulation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date postulation')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Candidat', verbose_name='Candidat concerné')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Offre', verbose_name='Offre concerné')),
            ],
            options={
                'ordering': ['date_postulation'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Spécialité')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='specialites',
            field=models.ManyToManyField(to='dashboard.Specialite'),
        ),
        migrations.AddField(
            model_name='offre',
            name='mot_cle',
            field=models.ManyToManyField(to='dashboard.MotCle', verbose_name='Mots clés offre'),
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together={('candidat', 'offre')},
        ),
    ]
