# Generated by Django 2.1.7 on 2019-03-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190307_1420'),
        ('dashboard', '0003_auto_20190308_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatOffre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Candidat', verbose_name='Candidat concerné')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Offre', verbose_name='Offre concerné')),
            ],
        ),
    ]
