# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-27 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_offre_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='categorie',
        ),
    ]
