# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-29 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_offre_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_limite',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 16, 16, 47, 568797, tzinfo=utc), verbose_name='Date limite du candidature'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 16, 16, 47, 568797, tzinfo=utc), verbose_name='Date de la publication'),
        ),
    ]
