# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190629_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_limite',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date limite du candidature'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la publication'),
        ),
    ]
