# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100)),
                ('prenom', models.CharField(default='Inconnu', max_length=100)),
                ('ddn', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('mail', models.CharField(blank=True, max_length=100, verbose_name='Adresse e-mail')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Mot de passe')),
                ('photo_profil', models.TextField(default='user.jpg', verbose_name='Photo de profil')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse physique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100)),
                ('prenom', models.CharField(default='Inconnu', max_length=100)),
                ('ddn', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('mail', models.CharField(blank=True, max_length=100, verbose_name='Adresse e-mail')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Mot de passe')),
                ('logo_societe', models.TextField(default='logo.jpg', verbose_name='Lodo de la société')),
                ('nom_societe', models.CharField(default='Anonyme', max_length=100, verbose_name='Nom de la société')),
                ('description', models.TextField(blank=True)),
                ('adresse_societe', models.TextField(blank=True, verbose_name='Adresse de la société')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
